# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest


before_script:
  - sed -i -r "s/VERSION 2.5.0/VERSION $CI_COMMIT_REF_NAME/g" Dockerfile

services:
  - docker:dind

##GitLab
build-master_gitlab:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build_gitlab:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  except:
    - master

##Docker
build-master_docker:
  stage: build
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker build --pull -t 313u/ansible .
    - docker push 313u/ansible
  only:
    - master

build_docker:
  stage: build
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker build --pull -t "313u/ansible:$CI_COMMIT_REF_NAME" .
    - docker push "313u/ansible:$CI_COMMIT_REF_NAME"
  except:
    - master
